{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2021-06-18T06:24:53.077728Z",
     "start_time": "2021-06-18T06:24:53.051973Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: VOCAB_PATH=/home/jupyter-v.pashentsev-2/2.matching/5/vocab.json\n",
      "env: EMB_PATH_KNRM=/home/jupyter-v.pashentsev-2/2.matching/5/embedings.pickle\n",
      "env: EMB_PATH_GLOVE=/home/jupyter-v.pashentsev-2/2.matching/5/data/glove.6B.50d.txt\n",
      "env: MLP_PATH=/home/jupyter-v.pashentsev-2/2.matching/5/mlp.pickle\n"
     ]
    }
   ],
   "source": [
    "%env VOCAB_PATH=/home/jupyter-v.pashentsev-2/2.matching/5/vocab.json\n",
    "%env EMB_PATH_KNRM=/home/jupyter-v.pashentsev-2/2.matching/5/embedings.pickle\n",
    "%env EMB_PATH_GLOVE=/home/jupyter-v.pashentsev-2/2.matching/5/data/glove.6B.50d.txt\n",
    "%env MLP_PATH=/home/jupyter-v.pashentsev-2/2.matching/5/mlp.pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "start_time": "2021-06-18T06:24:54.634Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"solution_final.py\" (lazy loading)\n",
      " * Environment: development\n",
      " * Debug mode: on\n",
      " * Running on http://127.0.0.1:11000/ (Press CTRL+C to quit)\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:25:13] \"\u001b[1m\u001b[35mGET /ping HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 338, in __call__\n",
      "    self._flush_bg_loading_exception()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 326, in _flush_bg_loading_exception\n",
      "    reraise(*exc_info)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 314, in _load_app\n",
      "    self._load_unlocked()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 330, in _load_unlocked\n",
      "    self._app = rv = self.loader()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 388, in load_app\n",
      "    app = locate_app(self, import_name, name)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 240, in locate_app\n",
      "    __import__(module_name)\n",
      "File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 65\n",
      "    return [self.vocab.get(t, 1) in  for t in tokens]\n",
      "                                       ^\n",
      "SyntaxError: invalid syntax\n",
      "127.0.0.1 - - [18/Jun/2021 08:25:56] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:26:19] \"\u001b[1m\u001b[35mPOST /update_index HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2464, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2450, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1867, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 146, in update_index\n",
      "    'index_size': solution.update_index(documents)}\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 86, in update_index\n",
      "    self.index = faiss.IndexIDMapD(self.index)\n",
      "AttributeError: module 'faiss' has no attribute 'IndexIDMapD'\n",
      " * Detected change in '/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py', reloading\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:26:53] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:27:03] \"\u001b[1m\u001b[35mPOST /update_index HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2464, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2450, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1867, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 146, in update_index\n",
      "    'index_size': solution.update_index(documents)}\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 87, in update_index\n",
      "    self.index.add_with_ids(embeddings,\n",
      "NameError: name 'embeddings' is not defined\n",
      " * Detected change in '/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py', reloading\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:28:19] \"\u001b[1m\u001b[35mGET /ping HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 338, in __call__\n",
      "    self._flush_bg_loading_exception()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 326, in _flush_bg_loading_exception\n",
      "    reraise(*exc_info)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 314, in _load_app\n",
      "    self._load_unlocked()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 330, in _load_unlocked\n",
      "    self._app = rv = self.loader()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 388, in load_app\n",
      "    app = locate_app(self, import_name, name)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/cli.py\", line 240, in locate_app\n",
      "    __import__(module_name)\n",
      "File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 102\n",
      "    return [str(i): self.documents[i]\n",
      "                  ^\n",
      "SyntaxError: invalid syntax\n",
      "127.0.0.1 - - [18/Jun/2021 08:28:42] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:28:52] \"\u001b[1m\u001b[35mPOST /update_index HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2464, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2450, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1867, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 145, in update_index\n",
      "    'index_size': solution.update_index(documents)}\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 88, in update_index\n",
      "    np.array(list(self.documents.keys())))\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/faiss/__init__.py\", line 111, in replacement_add_with_ids\n",
      "    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/faiss/swigfaiss.py\", line 5166, in swig_ptr\n",
      "    return _swigfaiss.swig_ptr(a)\n",
      "ValueError: did not recognize array type\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Detected change in '/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py', reloading\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:30:19] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:30:29] \"\u001b[37mPOST /update_index HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:31:57] \"\u001b[1m\u001b[35mPOST /query HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2464, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2450, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1867, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 128, in query\n",
      "    candidates = solution.search(q)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 103, in search\n",
      "    for i in document_ids]\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 103, in <listcomp>\n",
      "    for i in document_ids]\n",
      "TypeError: unhashable type: 'numpy.ndarray'\n",
      " * Detected change in '/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py', reloading\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:32:28] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:32:37] \"\u001b[37mPOST /update_index HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:32:37] \"\u001b[1m\u001b[35mPOST /query HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2464, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2450, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1867, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/tljh/user/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 128, in query\n",
      "    candidates = solution.search(q)\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 103, in search\n",
      "    for i in document_ids.reshape(-1)]\n",
      "  File \"/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py\", line 103, in <listcomp>\n",
      "    for i in document_ids.reshape(-1)]\n",
      "KeyError: 303345\n",
      " * Detected change in '/home/jupyter-v.pashentsev-2/2.matching/final/solution_final.py', reloading\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 189-611-939\n",
      "127.0.0.1 - - [18/Jun/2021 08:33:00] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:33:07] \"\u001b[37mPOST /update_index HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Jun/2021 08:33:08] \"\u001b[37mPOST /query HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "!FLASK_APP=solution_final.py FLASK_ENV=development flask run --port 11000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2021-06-17T21:23:46.158180Z",
     "start_time": "2021-06-17T21:16:26.768230Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"solution_final.py\"\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n",
      " * Running on http://127.0.0.1:11000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [17/Jun/2021 23:16:33] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [17/Jun/2021 23:16:35] \"\u001b[37mGET /ping HTTP/1.1\u001b[0m\" 200 -\n",
      "^C\n"
     ]
    }
   ],
   "source": [
    "!FLASK_APP=solution_final.py flask run --port 11000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
